### ISSUE TITLE
 Invalid URL

### ISSUE THREAD

**Issue by zyu** [nestjs/elasticsearch#101]
[Nest] 13136   - 2019-12-24 10:52:01 AM   [NestFactory] Starting Nest application...
[Nest] 13136   - 2019-12-24 10:52:01 AM   [InstanceLoader] TypegooseModule dependencies initialized +41ms
[Nest] 13136   - 2019-12-24 10:52:01 AM   [ExceptionHandler] Invalid URL: 192.168.0.201:32001 +2ms
TypeError [ERR_INVALID_URL]: Invalid URL: 192.168.0.201:32001
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at getUsernameAndPassword (E:\ngchina\demo\node_modules\@elastic\elasticsearch\index.js:233:38)
    at getAuth (E:\ngchina\demo\node_modules\@elastic\elasticsearch\index.js:224:16)
    at new Client (E:\ngchina\demo\node_modules\@elastic\elasticsearch\index.js:55:23)
    at new ElasticsearchService (E:\ngchina\demo\node_modules\@nestjs\elasticsearch\dist\elasticsearch.service.js:20:9)
    at Injector.instantiateClass (E:\ngchina\demo\node_modules\@nestjs\core\injector\injector.js:288:19)
    at callback (E:\ngchina\demo\node_modules\@nestjs\core\injector\injector.js:75:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by zyu** [comment]
must add http
