### ISSUE TITLE
request timeout

### ISSUE THREAD

**Issue by magdsnail** [nestjs/elasticsearch#382]
connect success,but insert error

(node:39385) UnhandledPromiseRejectionWarning: Error: Request timed out
    at YouzanService.trade_TradeCreate (/Users/mcee/Documents/work/xinzhouqi/scrm_nest/dist/youzan/youzan.service.js:116:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by magdsnail** [comment]
export module as other module user, error

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
